owner: kevinlangleyjr
repo: upptime

sites:
  - name: Kevin Langley Jr.
    url: https://kevinlangleyjr.dev
  - name: Kevin Langley Jr. Dot Com Redirect
    url: https://kevinlangleyjr.com
  - name: Scrum.to Marketing Site
    url: https://scrum.to
  - name: Scrum.to App
    url: https://app.scrum.to
  - name: Scrum.to API
    url: https://api.scrum.to

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kevin Langley Jr. Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime Data for Kevin Langley Jr.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
